display_name: FlClash
package_name: FlClash
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - ca-certificates
  - dbus-user-session
  - fonts-noto-cjk
  - gnome-keyring
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - libayatana-appindicator3-1
  - libglib2.0-bin
  - libkeybinder-3.0-0
  - libsecret-1-0

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash

categories:
  - Network

startup_notify: true
